#Control-OW
```{r}
control.dis<-15
control.nodis<-21
ow.dis<-3
ow.nodis<-33

my.table<-as.table(rbind(c(control.dis,control.nodis),c(ow.dis,ow.nodis))) 

dimnames(my.table)<-list(exposure=c("control","ow"),result=c("disease","no.disease")) 

my.table 

chisq.test(my.table)$expected

chisq.test(my.table)
```

#Control-OA
```{r}
control.dis<-15
control.nodis<-21
oa.dis<-4
oa.nodis<-32

my.table<-as.table(rbind(c(control.dis,control.nodis),c(oa.dis,oa.nodis))) 

dimnames(my.table)<-list(exposure=c("control","oa"),result=c("disease","no.disease")) 

my.table 

chisq.test(my.table)$expected

chisq.test(my.table)
```

#Control-OAOW
```{r}
control.dis<-15
control.nodis<-21
oaow.dis<-16
oaow.nodis<-20

my.table<-as.table(rbind(c(control.dis,control.nodis),c(oaow.dis,oaow.nodis))) 

dimnames(my.table)<-list(exposure=c("control","oaow"),result=c("disease","no.disease")) 

my.table 

chisq.test(my.table)$expected

chisq.test(my.table)
```

#OW-OA
```{r}
ow.dis<-3
ow.nodis<-33
oa.dis<-4
oa.nodis<-32

my.table<-as.table(rbind(c(ow.dis,ow.nodis),c(oa.dis,oa.nodis))) 

dimnames(my.table)<-list(exposure=c("ow","oa"),result=c("disease","no.disease")) 

my.table 

chisq.test(my.table)$expected

chisq.test(my.table)
```

#OW-OAOW
```{r}
oaow.dis<-16
oaow.nodis<-20
ow.dis<-3
ow.nodis<-33

my.table<-as.table(rbind(c(oaow.dis,oaow.nodis),c(ow.dis,ow.nodis))) 

dimnames(my.table)<-list(exposure=c("oaow","ow"),result=c("disease","no.disease")) 

my.table 

chisq.test(my.table)$expected

chisq.test(my.table)
```

#OA-OAOW
```{r}
oa.dis<-4
oa.nodis<-32
oaow.dis<-16
oaow.nodis<-20

my.table<-as.table(rbind(c(oa.dis,oa.nodis),c(oaow.dis,oaow.nodis))) 

dimnames(my.table)<-list(exposure=c("oa","oaow"),result=c("disease","no.disease")) 

my.table 

chisq.test(my.table)$expected

chisq.test(my.table)
```
