
#Control-OA
```{r}
control.dis<-5
control.nodis<-4
oa.dis<-1
oa.nodis<-8

my.table<-as.table(rbind(c(control.dis,control.nodis),c(oa.dis,oa.nodis))) 

dimnames(my.table)<-list(exposure=c("control","oa"),result=c("disease","no.disease"))

my.table

fisher.test(my.table)

chisq.test(my.table)
```

#Control-OW
```{r}
control.dis<-5
control.nodis<-4
ow.dis<-4
ow.nodis<-5

my.table<-as.table(rbind(c(control.dis,control.nodis),c(ow.dis,ow.nodis))) 

dimnames(my.table)<-list(exposure=c("control","ow"),result=c("disease","no.disease"))

my.table

fisher.test(my.table)

chisq.test(my.table)
```

#Control-OAOW
```{r}
control.dis<-5
control.nodis<-4
oaow.dis<-3
oaow.nodis<-6

my.table<-as.table(rbind(c(control.dis,control.nodis),c(oaow.dis,oaow.nodis))) 

dimnames(my.table)<-list(exposure=c("control","oaow"),result=c("disease","no.disease"))

my.table

fisher.test(my.table)

chisq.test(my.table)
```

#OW-OA
```{r}
ow.dis<-4
ow.nodis<-5
oa.dis<-1
oa.nodis<-8

my.table<-as.table(rbind(c(ow.dis,ow.nodis),c(oa.dis,oa.nodis))) 

dimnames(my.table)<-list(exposure=c("ow","oa"),result=c("disease","no.disease")) 

my.table

fisher.test(my.table)

chisq.test(my.table)
```

#OW-OAOW
```{r}
ow.dis<-4
ow.nodis<-5
oaow.dis<-3
oaow.nodis<-6

my.table<-as.table(rbind(c(ow.dis,ow.nodis),c(oaow.dis,oaow.nodis))) 

dimnames(my.table)<-list(exposure=c("ow","oaow"),result=c("disease","no.disease"))

my.table

fisher.test(my.table)

chisq.test(my.table)
```

#OA-OAOW
```{r}
oaow.dis<-3
oaow.nodis<-6
oa.dis<-1
oa.nodis<-8

my.table<-as.table(rbind(c(oaow.dis,oaow.nodis),c(oa.dis,oa.nodis))) #combine counts into a contingency table

dimnames(my.table)<-list(exposure=c("oaow","oa"),result=c("disease","no.disease")) #add names to make it easier to read

my.table # output and make sure it looks right

fisher.test(my.table)

chisq.test(my.table)
```
